name: "Submit Directory"
description: Submit Missing directories
title: "Submit Directory"
labels: ["Directory Submission"
]
assignees:
  - araafroyall
body:
  - type: markdown
    attributes:
      value: |
        Please Don't Change the Title. & The marked options with * must be filled. 
  - type: markdown
    attributes:
      value: |
        Fill This Forum , Wait for Review , Get Your Activation Key, For Any Help [Contact Developer](https://t.me/AraafRoyall)
  - type: markdown
    attributes:
      value: |
        Fill forum Only If you made payment [Payment Page](https://github.com/araafroyall/Cleaner-Pro-Lite/blob/main/PaymentMethods).




  - type: textarea
    id: dirs
    attributes:
      label: "Submit Directory"
      description: Please enter Comments or Other information which you want to tell
      value: 
      render: bash
    validations:
      required: false