name: "Feature Request"
description: Suggest New Features.
title: "‎ "
labels: [
  "Feature Request"
]
body:

  - type: textarea
    id: featr
    attributes:
      label: "Explain Feature"
      description: Please Explain in detail which Feature which you want 
      value: 
      render: info
    validations:
      required: true



  - type: textarea
    id: optnal
    attributes:
      label: "Comment or Extra Info"
      description: Please Explain or tell addition information here 
      placeholder: Optionally you can Attach screenshots , video , etc...
    validations:
      required: False


  - type: dropdown
    id: osh
    attributes:
      label: "Android Version"
      description: Please Select Your Android Version
      multiple: true
      options:
        - Any Android
        - Android 6
        - Android 7
        - Android 8
        - Android 9
        - Android 10
        - Android 11
        - Android 12
        - Android 13
        - Android 14
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: "App Version"
      description: 
      multiple: true
      options:
        - v3.0
        - v3.1
    validations:
      required: false