name: "Premium Forum"
description: Fill This Forum to get Activation Key
title: "Premium Activation Key"
labels: [
  "Activation Key"
]
body:
  - type: markdown
    attributes:
      value: |
        Please Don't Change the Title



  - type: dropdown
    id: method
    attributes:
      label: "Payment Method"
      description: Select Your Payment Method
      multiple: true
      options:
        - Paypal
        - UPI
        - Crypto or BTC or Binance
        - Others
    validations:
      required: true


  - type: input
    attributes:
      label: Transaction id or Hash
    validations:
      required: true



  - type: input
    id: stringid
    attributes:
      label: "Paste String"
      description: Paste String text here, you can find this in cleaner lite app at premium activiy page
      placeholder: ex. https://github.com/USERNAME/REPO-NAME
    validations:
      required: true





  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true



  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: "Browsers"
      description: What browsers are you seeing the problem on ?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: What is the impacted environment ?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: false




  - type: input
    attributes:
      label: Android version/Android 版本
    validations:
      required: true




  - type: input
    id: reprod-url
    attributes:
      label: "Reproduction URL"
      description: Please enter your GitHub URL to provide a reproduction of the issue
      placeholder: ex. https://github.com/USERNAME/REPO-NAME
    validations:
      required: true